apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: communityservice
  labels:
    app: communityservice
spec:
  selector:
    matchLabels:
      app: communityservice
  endpoints:
    - port: metrics
      path: /metrics
      interval: 15s
