apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: chatservice
spec:
  selector:
    matchLabels:
      app: chatservice
  endpoints:
    - port: http
      path: /metrics
      interval: 15s
