apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: notificationservice
  labels:
    app: notificationservice
spec:
  selector:
    matchLabels:
      app: notificationservice
  endpoints:
    - port: metrics
      path: /metrics
      interval: 15s
