apiVersion: v1
kind: Service
metadata:
  name: notificationservice
  labels:
    app: notificationservice
spec:
  selector:
    app: notificationservice
  ports:
    - name: http
      protocol: TCP
      port: 8086
      targetPort: 8086
    - name: metrics
      protocol: TCP
      port: 9090
      targetPort: 9090
