apiVersion: route.openshift.io/v1
kind: Route
metadata:
  name: userservice-minio-api
spec:
  to:
    kind: Service
    name: minio
    weight: 100
  port:
    targetPort: api
  tls:
    termination: edge
    insecureEdgeTerminationPolicy: Redirect
  wildcardPolicy: None
