apiVersion: v1
kind: Service
metadata:
  name: userservice
  labels:
    app: userservice
spec:
  selector:
    app: userservice
  ports:
    - name: http
      protocol: TCP
      port: 8081
      targetPort: 8081
    - name: metrics
      protocol: TCP
      port: 9090
      targetPort: 9090
