apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: userservice
  labels:
    app: userservice
    release: prometheus
spec:
  selector:
    matchLabels:
      app: userservice
  endpoints:
    - port: metrics
      path: /metrics
      interval: 15s
