apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: videoservice
  labels:
    app: videoservice
spec:
  selector:
    matchLabels:
      app: videoservice
  endpoints:
    - port: http
      path: /metrics
      interval: 15s
