# Add this workflow to your VideoService repository
# Path: .github/workflows/update-deployment.yml

name: Update Deployment Manifest

on:
  workflow_run:
    workflows: ["CI/CD"] # Replace with your Docker build workflow name
    types:
      - completed
    branches:
      - main
      - dev

jobs:
  update-prod-manifest:
    if: github.event.workflow_run.conclusion == 'success' && github.event.workflow_run.head_branch == 'main'
    uses: coendv/simpleSlideshow-deploy/.github/workflows/update-image-digest.yml@main
    with:
      service-name: VideoService
      image-name: ghcr.io/coendv/group1-videoservice
      environment: prod
      branch: main
    secrets:
      DEPLOY_REPO_TOKEN: ${{ secrets.DEPLOY_REPO_TOKEN }}

  update-test-manifest:
    if: github.event.workflow_run.conclusion == 'success' && github.event.workflow_run.head_branch == 'dev'
    uses: coendv/simpleSlideshow-deploy/.github/workflows/update-image-digest.yml@main
    with:
      service-name: VideoService
      image-name: ghcr.io/coendv/group1-videoservice
      environment: test
      branch: dev
    secrets:
      DEPLOY_REPO_TOKEN: ${{ secrets.DEPLOY_REPO_TOKEN }}
